#!/bin/sh
# Cross-compiles the Restow agent for Linux and macOS (amd64 and arm64), fetches
# the pinned restic release for each target with SHA-256 verification, and
# writes SHA256SUMS. Output layout:
#
#   dist/<os>-<arch>/restow-agent
#   dist/<os>-<arch>/restic
#   dist/<os>-<arch>/THIRD_PARTY_NOTICES.txt   (the license of the agent and the
#                                    notices of restic and the Go modules in it,
#                                    from THIRD_PARTY_NOTICES.txt in this folder;
#                                    the installers put it next to the binaries)
#   dist/<os>-<arch>/SHA256SUMS      (the files of one target)
#   dist/SHA256SUMS                  (all files, paths relative to dist/; the
#                                     release signature covers this file)
#   dist/VERSION, dist/RESTIC_VERSION
#
# The release signature (dist/SHA256SUMS.sig) is made offline by the
# maintainer, never by this script; see agent/README.md, "Release signing".
# Release versions are refused while release-signing.pub holds the placeholder.
#
# If a Go toolchain is on PATH it is used; otherwise the script runs itself in
# the pinned golang Docker image (Go is not required on the host).
#
# Usage: ./build.sh [--version X.Y.Z] [--out DIR] [--targets "linux-amd64 ..."] [--no-restic]
set -eu

AGENT_DIR=$(cd "$(dirname "$0")" && pwd)
# shellcheck source=scripts/lib.sh
. "$AGENT_DIR/scripts/lib.sh"

VERSION="${RESTOW_VERSION:-0.0.0-dev}"
OUT="$AGENT_DIR/dist"
TARGETS="linux-amd64 linux-arm64 darwin-amd64 darwin-arm64"
WITH_RESTIC="${RESTOW_BUILD_WITH_RESTIC:-1}"

while [ $# -gt 0 ]; do
  case "$1" in
    --version) VERSION="${2:?--version needs a value}"; shift 2 ;;
    --out) OUT="${2:?--out needs a value}"; shift 2 ;;
    --targets) TARGETS="${2:?--targets needs a value}"; shift 2 ;;
    --no-restic) WITH_RESTIC=0; shift ;;
    -h | --help) sed -n '2,24p' "$0"; exit 0 ;;
    *) die "unknown option $1" ;;
  esac
done
VERSION="${VERSION#v}"
# Generated by scripts/third-party-notices.mjs in the repository; ships with every target.
NOTICES="THIRD_PARTY_NOTICES.txt"
[ -s "$AGENT_DIR/$NOTICES" ] || die "$NOTICES is missing in $AGENT_DIR (node scripts/third-party-notices.mjs writes it)"
case "$VERSION" in
  [0-9]*.[0-9]*.[0-9]* | 0.0.0-dev) ;;
  *) die "version '$VERSION' is not major.minor.patch" ;;
esac
case "$OUT" in /*) ;; *) OUT="$PWD/$OUT" ;; esac

# A release must be verifiable: the agent embeds release-signing.pub and the
# install scripts check the release signature with it. Only development builds
# (version *-dev) may be built while the file still holds the placeholder.
case "$VERSION" in
  *-dev | *-dev.*) ;;
  *)
    grep -q '^ssh-ed25519 ' "$AGENT_DIR/release-signing.pub" ||
      die "release build $VERSION refused: release-signing.pub still holds the placeholder. Create the release signing key first (agent/README.md, \"Release signing\") and commit its public half."
    ;;
esac

# Run inside Docker when there is no Go toolchain on the host.
if ! command -v go >/dev/null 2>&1; then
  command -v docker >/dev/null 2>&1 || die "neither go nor docker found"
  case "$OUT" in
    "$AGENT_DIR"/*) ;;
    *) die "without a local Go toolchain --out must be inside $AGENT_DIR" ;;
  esac
  rel="${OUT#"$AGENT_DIR"/}"
  exec docker run --rm \
    -v "$AGENT_DIR":/src -w /src \
    -v restow-agent-gomod:/go/pkg/mod -v restow-agent-gocache:/root/.cache/go-build \
    -e RESTOW_COMMIT="${RESTOW_COMMIT:-$(git -C "$AGENT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)}" \
    -e SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-}" \
    -e RESTOW_BUILD_WITH_RESTIC="$WITH_RESTIC" \
    "$GO_IMAGE" sh ./build.sh --version "$VERSION" --out "/src/$rel" --targets "$TARGETS"
fi

COMMIT="${RESTOW_COMMIT:-$(git -C "$AGENT_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
if [ -n "${SOURCE_DATE_EPOCH:-}" ]; then
  DATE=$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -r "$SOURCE_DATE_EPOCH" +%Y-%m-%dT%H:%M:%SZ)
else
  DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
fi
PKG=github.com/restow-backup/restow/agent/internal/buildinfo
LDFLAGS="-s -w -X $PKG.Version=$VERSION -X $PKG.Commit=$COMMIT -X $PKG.Date=$DATE"

echo "Building restow-agent $VERSION ($COMMIT) with $(go version)"
rm -rf "$OUT"
mkdir -p "$OUT"
cd "$AGENT_DIR"

host_os=$(go env GOHOSTOS)
host_arch=$(go env GOHOSTARCH)

for target in $TARGETS; do
  os="${target%-*}"
  arch="${target#*-}"
  case "$os-$arch" in
    linux-amd64 | linux-arm64 | darwin-amd64 | darwin-arm64) ;;
    *) die "unsupported target $target (linux and darwin on amd64 and arm64 only)" ;;
  esac
  dir="$OUT/$target"
  mkdir -p "$dir"
  echo "== $target"
  CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" go build -trimpath -buildvcs=false \
    -ldflags "$LDFLAGS" -o "$dir/restow-agent" ./cmd/restow-agent
  if [ "$WITH_RESTIC" = 1 ]; then
    fetch_tool restic "$os" "$arch" "$dir/restic"
    if [ "$os" = "$host_os" ] && [ "$arch" = "$host_arch" ]; then
      got=$("$dir/restic" version | sed -n 's/^restic \([0-9][0-9.]*\).*/\1/p')
      [ "$got" = "$RESTIC_VERSION" ] || die "restic for $target reports version '$got', pinned $RESTIC_VERSION"
      "$dir/restow-agent" version --short | grep -qx "$VERSION" || die "restow-agent for $target reports a different version"
      echo "   verified: restic $got and restow-agent $VERSION run on this host"
    fi
  fi
  cp "$AGENT_DIR/$NOTICES" "$dir/$NOTICES"
  chmod 0644 "$dir/$NOTICES"
  (
    cd "$dir"
    # restic is absent with --no-restic. Do not write this as `[ -f ... ] && ...`:
    # under set -e a false test would end the loop with status 1 and kill the
    # script without a message.
    for f in restow-agent restic "$NOTICES"; do
      if [ -f "$f" ]; then
        sum=$(sha256_file "$f")
        [ -n "$sum" ] || die "cannot compute the SHA-256 of $dir/$f"
        printf '%s  %s\n' "$sum" "$f"
      fi
    done > SHA256SUMS
  )
done

(
  cd "$OUT"
  for target in $TARGETS; do
    while read -r sum name; do
      printf '%s  %s/%s\n' "$sum" "$target" "$name"
    done < "$target/SHA256SUMS"
  done > SHA256SUMS
)
printf '%s\n' "$VERSION" > "$OUT/VERSION"
printf '%s\n' "$RESTIC_VERSION" > "$OUT/RESTIC_VERSION"
echo "Done. Artifacts in $OUT"
