import { defineConfig } from "drizzle-kit";

// Drizzle Kit reads this file directly (its own TS loader), so it lives at the
// package root and is intentionally outside the `src` tsconfig `include`.
// The connection string never carries a default value: it comes from the
// environment at generate time and is never committed. Migrations are applied
// by `pnpm db:migrate` (src/migrate.ts), which also installs the RLS policies and
// the database roles; drizzle-kit only needs the owner connection for `studio`.
export default defineConfig({
  dialect: "postgresql",
  // Point at the compiled schema: the source uses ESM ".js" import specifiers,
  // which drizzle-kit's loader does not remap to ".ts". The compiled dist has real
  // ".js" files, so `generate` builds first (see the package "generate" script).
  schema: "./dist/schema/index.js",
  out: "./drizzle",
  dbCredentials: {
    url: process.env.DATABASE_MIGRATION_URL ?? "",
  },
  // better-auth migrations are generated by its own CLI (see src/schema/index.ts)
  // and applied against the same database alongside the migrations in ./drizzle.
  verbose: true,
  strict: true,
});
